patients <- suppressWarnings(DBI::dbReadTable(conn, "patients_patient"))
centers <- suppressWarnings(DBI::dbReadTable(conn, "centers_center"))
gender <- suppressWarnings(DBI::dbReadTable(conn, "patients_gender"))
caregiver <- suppressWarnings(DBI::dbReadTable(conn, "patients_caregiver"))
condition <- suppressWarnings(DBI::dbReadTable(conn, "patients_patientcondition"))
profession <- suppressWarnings(DBI::dbReadTable(conn, "patients_profession"))
education <- suppressWarnings(DBI::dbReadTable(conn, "patients_education"))
visit <- suppressWarnings(
  DBI::dbReadTable(conn, "patients_patientvisit") |>
    dplyr::mutate(
      visit_date = lubridate::as_date(visit_date)
    )
)
bad_habit <- suppressWarnings(DBI::dbReadTable(conn, "patients_badhabit"))
underlying_disease <- suppressWarnings(DBI::dbReadTable(conn, "patients_underlyingdisease"))
cardiopathy <- suppressWarnings(DBI::dbGetQuery(conn, "SELECT * FROM patients_cardiopathy"))
device_testing_info <- suppressWarnings(DBI::dbReadTable(conn, "patients_devicetestinginfo"))
mv_type <- suppressWarnings(DBI::dbReadTable(conn, "patients_mvtype"))
mask_type <- suppressWarnings(DBI::dbReadTable(conn, "patients_masktype"))
device_selection <- suppressWarnings(DBI::dbReadTable(conn, "patients_deviceselection"))
check_cause <- suppressWarnings(DBI::dbReadTable(conn, "patients_checkcause"))
checked_by <- suppressWarnings(DBI::dbReadTable(conn, "patients_checkedby"))
ventilation_type <- suppressWarnings(DBI::dbReadTable(conn, "patients_ventilationtype"))
breath_and_sleep_test <- suppressWarnings(DBI::dbReadTable(conn, "patients_breathandsleeptest"))
breath_and_sleep_test_clinical_symptoms <- suppressWarnings(DBI::dbReadTable(conn, "patients_breathandsleeptest_clinical_symptoms"))
clinical_symptom <- suppressWarnings(DBI::dbReadTable(conn, "patients_clinicalsymptom"))
period_of_usage <- suppressWarnings(DBI::dbReadTable(conn, "patients_periodofusage"))
treatment_provider <- suppressWarnings(DBI::dbReadTable(conn, "patients_treatmentprovider"))
xoth <- suppressWarnings(DBI::dbReadTable(conn, "patients_xoth"))
ventilation_reason <- suppressWarnings(DBI::dbReadTable(conn, "patients_ventilationreason"))
ventilation_status <- suppressWarnings(DBI::dbReadTable(conn, "patients_ventilationstatus"))
ventilation_type <- suppressWarnings(DBI::dbReadTable(conn, "patients_ventilationtype"))
invasive_system_estimation <- suppressWarnings(DBI::dbReadTable(conn, "patients_invasivesystemestimation"))
tracheostomy_type <- DBI::dbReadTable(conn, "patients_tracheostomytype")

characteristics <- suppressWarnings(DBI::dbReadTable(conn, "patients_patientcharacteristics"))
patient_ventilation <- suppressWarnings(DBI::dbReadTable(conn, "patients_patientventilation"))

message("Loaded all required tables from database...")
